<html><body><p>The trouble seems to be implement.gcmap and implement_9.gcmap. These are bothe empty, and trigger the assertion error.<br><br>Running trackgcroot as the Makefile does, but without those two files, permits compilation to continue, but linking fails with undefined references to various symbols with the prefix 'pypy_g_'.<br><br>I suspected the changes might have invalidated the old .gcmap files, so I tried removing them, and got this when it tried to generate implement.gcmap:<br><br>Traceback (most recent call last):<br>  File "/home/chshrcat/build/pypy-trunk/pypy/translator/c/gcc/trackgcroot.py", line 1214, in &lt;module&gt;<br>    tracker.process(f, g, filename=fn)<br>  File "/home/chshrcat/build/pypy-trunk/pypy/translator/c/gcc/trackgcroot.py", line 229, in process<br>    lines = self.process_function(lines, entrypoint, filename)<br>  File "/home/chshrcat/build/pypy-trunk/pypy/translator/c/gcc/trackgcroot.py", line 244, in process_function<br>    table = tracker.computegcmaptable(self.verbose)<br>  File "/home/chshrcat/build/pypy-trunk/pypy/translator/c/gcc/trackgcroot.py", line 285, in computegcmaptable<br>    self.parse_instructions()<br>  File "/home/chshrcat/build/pypy-trunk/pypy/translator/c/gcc/trackgcroot.py", line 365, in parse_instructions<br>    insn = meth(line)<br>  File "/home/chshrcat/build/pypy-trunk/pypy/translator/c/gcc/trackgcroot.py", line 741, in visit_jmp<br>    self.conditional_jump(line)<br>  File "/home/chshrcat/build/pypy-trunk/pypy/translator/c/gcc/trackgcroot.py", line 757, in conditional_jump<br>    raise UnrecognizedOperation(line)<br>__main__.UnrecognizedOperation:         jmp     T.14141</p></body></html>